### ISSUE TITLE
Uncaught ReferenceError: process is not defined (jsondiffpatch)

### ISSUE THREAD

**Issue by maylortaylor** [jotaijs/jotai-devtools#100]
Whenever i add the <DevTool /> component, my app gets an error.
using version -- "jotai-devtools": "^0.6.2"

`
runtime.js:39 Uncaught ReferenceError: process is not defined
    at eval (index.js:6:13)
    at ./node_modules/jsondiffpatch/node_modules/supports-color/index.js (main.js:139097:1)
    at options.factory (runtime.js:620:31)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:277:21)
    at eval (index.js:3:52)
    at ./node_modules/jsondiffpatch/node_modules/chalk/source/index.js (main.js:139023:1)
    at options.factory (runtime.js:620:31)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:277:21)
`

**Comment by arjunvegda** [comment]
Hi @maylortaylor 

That's odd, we fixed [this issue a while ago](https://github.com/jotaijs/jotai-devtools/issues/82#issuecomment-1685451604). Could you please try removing `jotai-devtools` completely and re-installing it? I wonder if it's a caching issue.

**Comment by maylortaylor** [comment]
> Hi @maylortaylor
> 
> That's odd, we fixed [this issue a while ago](https://github.com/jotaijs/jotai-devtools/issues/82#issuecomment-1685451604). Could you please try removing `jotai-devtools` completely and re-installing it? I wonder if it's a caching issue.

I just did this script `rm -rf node_modules && rm -rf packge-lock.json && npm cache clean --force && npm install` and updated to `jotai-devtools: '^0.6.3'` and i am still getting this error whenever i insert `<DevTools />` into my `App.tsx` file. If i remove that line, the app runs without any errors.

![image](https://github.com/jotaijs/jotai-devtools/assets/7232060/611a420d-642d-4f73-857c-1aaf73a54475)

**Comment by arjunvegda** [comment]
Could @maylortaylor help create a small repro? https://csb.jotai.org/

**Comment by arjunvegda** [comment]
Closing this for now, I'm assuming it fixed itself? Please feel free to reopen it if the issue still persists.
